name: whatifapp
description: >
  WhatIfApp - App Flutter con onboarding personalizzato e deploy su GitHub Pages.
publish_to: "none" # non pubblicare su pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # librerie comuni
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.3
  provider: ^6.0.5
  http: ^1.1.0
  go_router: ^6.5.9
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
assets:
    - assets/images/whataf_logo_bar.svg
    - assets/images/whatif_logo_main.svg
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/
  assets:
    - assets/images/whataf_logo_bar.svg
    - assets/images/whatif_logo_main.svg
    - assets/
    - assets/svg/

flutter:
  uses-material-design: true
  assets:
    - assets/images/whataf_logo_bar.svg
    - assets/images/whatif_logo_main.svg
    - assets/whatif_door.png
    - assets/whatif_bar.png

flutter:
  assets:
    - assets/images/whatif_door.svg
    - assets/images/whatif_bar.svg
    - assets/logos/whatif_door.svg
    - assets/logos/whatif_bar.svg

flutter:
  uses-material-design: true
  assets:
    - assets/logos/whatif_icon_door.svg

flutter:
  uses-material-design: true
  assets:
    - assets/logos/whatif_icon_beer.svg
