name: whatifapp
description: >-
  WhatIfApp - App Flutter con onboarding personalizzato e deploy su GitHub Pages.
publish_to: "none" # non pubblicare su pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter

  # Librerie comuni
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  shared_preferences: ^2.5.3
  provider: ^6.0.5
  http: ^1.1.0
  go_router: ^6.5.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
